### ISSUE TITLE
Remove "Ignore player" functionality

### ISSUE THREAD

**Issue by ilya-murzinov** [artem-zinnatullin/android-wail-app#154]
I'm having second thoughts about this "Ignore player" functionality.
As many players broadcast their intents with the wrong package name (e.g. com.android.music) it's not safe to ignore them based on this information.
Also, if we ever implement #8, the problem becomes more serious because I personally didn't figure out how to detect which player is actually playing.
So, even though it's a nice feature, may be we should just remove it.

@artem-zinnatullin, I need you to resolve this.

**Comment by artem-zinnatullin** [comment]
I had same thoughts, when I played with #8 I also didn't find how to detect current player. I think, we can remove this "feature".

**Comment by ilya-murzinov** [comment]
Instead of this, I think we should add "Unscrobble track" and "Remove track from library" features. Not quite the same, but at least something.

**Comment by artem-zinnatullin** [comment]
Okay, why not.
20 июня 2015 г. 11:40 AM пользователь "Ilya Murzinov" <
notifications@github.com> написал:

**Comment by insintesi** [comment]
To be frank, this is exactly why I won’t update the app. The ability to exclude certain apps was *the* killer feature, and it worked excellent, at least on my side.

I use Rdio to stream songs, which already provides *one* option to scrobble across all platforms, unlike Spotify where scrobbling has to be activated on each platform respectively: desktop, mobile, tablet etc.

The new version of WAIL would lead to duplicates that I would have to remove every single time. I hope you understand this is no option to me. I also hope the old version lasts forever, otherwise I’d have to return to the original Last.fm app (shudder!).

**Comment by ilya-murzinov** [comment]
@insintesi, thanks for your feedback.
I created issue #170, we will try to bring this feature back in 0.7.4.

**Comment by insintesi** [comment]
Thank you, I really appreciate that. Also, many thanks for the app and keeping Last.fm on Android alive!

**Comment by artem-zinnatullin** [comment]
BTW, if you need this feature feel free to download previous version of
WAIL from GitHub releases, we store signed versions there, so you can
install them safely.
1 июля 2015 г. 3:32 PM пользователь "insintesi" <notifications@github.com>
написал:
